spring:
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              H2Dialect