spring:
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect:
          org:
            hibernate:
              dialect:
                H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework: info